version: '3.8'
services:
  node:
    image: 'node:latest'
    container_name: project_node
    working_dir: '/home/app'
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    links:
      - mysql
    volumes:
      - './app:/home/app'
    networks:
      - my-network
  mysql:
    image: 'mariadb:latest'
    container_name: project_mysql
    env_file:
      - .env
    ports:
      - '3309:3309'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge