version: '3.3'
services:
  node:
    container_name: project_node_workshop
    image: 'node:latest'
    working_dir: /home/node/app
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - './src:/home/node/app'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
