version: '3.8'
services:
  node:
    image: 'node:latest'
    container_name: project_node
    working_dir: '/home/app'
    env_file:
      - .env
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    ports:
      - '3000:3000'
      - '5000:5000'
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - './app:/home/app'
    networks:
      - my-network
  mysql:
    image: 'mariadb:latest'
    container_name: project_mysql
    env_file:
      - .env
    ports:
      - '3309:3306'
    networks:
      - my-network
    volumes:
    - ./app/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mysqladmin','ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
networks:
  my-network:
    driver: bridge